<?php

	require_once "TiE_Config.inc";
	GLOBAL $_PATH;
	require_once "TiE_Defines.inc";
	require_once $_PATH['FRAMEWORK']['DB']."TiE_Connection.class";
	require_once $_PATH['FRAMEWORK']['DB']."TiE_Query.class";
	require_once $_PATH['FRAMEWORK']['DB']."TiE_Db.class";
	require_once $_PATH['FRAMEWORK']['LAYOUT']."TiE_Layout.class";
	require_once $_PATH['FRAMEWORK']['SYSTEM']."TiE_Program.class";
	require_once $_PATH['FRAMEWORK']['HTML']."TiE_HTML_components.class";
    require_once $_PATH['FRAMEWORK']['JQUERY']."TiE_JQuery.class";
    require_once $_PATH['FRAMEWORK']['JQUERY']."TiE_JQuery_components.class";
    require_once $_PATH['FRAMEWORK']['MVC_CONTROLLER']."TiE_Controller.class";
	require_once $_PATH['FRAMEWORK']['MVC_MODEL']."TiE_Model.class";
	require_once $_PATH['FRAMEWORK']['MVC_VIEW']."TiE_View.class";
	require_once $_PATH['FRAMEWORK']['EXCEPTIONS']."TiE_Exception.class";
	require_once $_PATH['FRAMEWORK']['ERROR']."TiE_Error.class";
	require_once $_PATH['FRAMEWORK']['ERROR']."TiE_Log.class";
	require_once $_PATH['FRAMEWORK']['FILE']."TiE_File.class";	

?>